modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
issueTrackerURL="http://github.com/itsmeow/betteranimalsplus/issues" #optional
displayURL="https://www.curseforge.com/minecraft/mc-mods/betteranimalsplus" #optional
logoFile="betteranimalsplus.png" #optional
credits="Cybercat5555: Design, Modeling, Texturing, Ideas; its_meow: Programming, AI, Functionality" #optional
authors="cybercat5555, its_meow (hiotewdew)" #optional
license="CC BY-NC-SA 4.0 https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode"
[[mods]] #mandatory
modId="betteranimalsplus" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Better Animals Plus" #mandatory
# The description text for the mod (multi line!) (#mandatory)
description='''
Companion mod to Better Animals adding new creatures with the Better Animals art style.'''
[[dependencies.betteranimalsplus]]
    modId="forge"
    mandatory=true
    versionRange="[34.1.21,)"
    ordering="NONE"
    side="BOTH"