name: Build Commit
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - { name: 'Set up JDK 16', uses: actions/setup-java@v2, with: { distribution: 'adopt', java-version: '16' } }
      - uses: burrunan/gradle-cache-action@v1
        name: Build with Gradle
        id: build
        env:
          MAVEN_PASSWORD: "${{secrets.MAVEN_PASSWORD}}"
          MAVEN_URL: "${{secrets.MAVEN_URL}}"
          MAVEN_USER: "${{secrets.MAVEN_USER}}"
          SHA_VERSION: '${{ github.event.after }}'
        with:
          arguments: "build publish"
          gradle-version: "wrapper"